### ISSUE TITLE
HMR not working?

### ISSUE THREAD

**Issue by mjyoung** [nightwolfz/mobx-starter#7] opened 2016-09-14 18:59 UTC
Hi there!

First of all, thanks for this starter kit. It looks great. I am having some issues getting hot module replacement to work, however.

My steps were:

```
1. git clone
2. npm install
3. npm run dev
4. change the HTML static content in About.js
```

[HMR] says it updated the modules but the browser doesn't show the DOM updated, and there's some warning about React-Router (don't know if relevant):
![image](https://cloud.githubusercontent.com/assets/868346/18525762/7dd77e14-7a83-11e6-9f6f-4b2df2c57eef.png)

If I manually refresh with `command + R` then the view is properly updated.

Any thoughts?

**Comment by nightwolfz** [comment] 2016-09-14 19:13
I didn't notice that before... I'll take a look tomorrow

**Comment by mjyoung** [comment] 2016-09-14 21:51
Thanks! Maybe this could be of help:
https://github.com/reactjs/react-router-redux/issues/179

**Comment by nightwolfz** [comment] 2016-09-15 06:47
I pushed some changes into master. You should still get the `react-router` warning but the HMR should work again.

Once react-router v4 is out of alpha, we should not see that error anymore.

Let me know if that fixes it for you and don't forget to npm install :)

**Comment by omaksi** [comment] 2016-09-15 09:15
I can confirm HMR working now, thanks! Although the error appearing on each change is not great as one can get 100's of errors in active development, making it hard to spot a real error.

**Comment by omaksi** [comment] 2016-09-15 12:18
Also on `/register` and `/login` I get 
`Error: MobX observer: Store 'router' is not available! Make sure it is provided by some Provider`

**Comment by mjyoung** [comment] 2016-09-15 15:27
I confirm _reloading_ is working, but is HMR actually working? One of the benefits of HMR is supposed to be that it preserves the state as it injects the diff into the DOM, but I don't see it preserving state, for example when I have form inputs filled in.

Edit: nevermind. The form input disappears but that's probably because it's not tied to any particular state. I put in a simple ClickCount and that is preserved when HMR does its thing.

**Comment by nightwolfz** [comment] 2016-09-15 17:19
@omaksi My mistake, I renamed router to history to keep naming consistent with `inferno-starter` project. That'll teach me not to make late-night changes :)

I will see if there's a way to silence the warnings. Otherwise I can migrate the whole thing to use react-router v4 if there are no objections.

**Comment by omaksi** [comment] 2016-09-15 17:37
Sure, no objections here. Although from what I've heard it's not a drop-in replacement, so it might take a bit of work. Maybe It'd be worth it to look for a way to make it work with 2.x first. Up to you ofc :)

**Comment by nightwolfz** [comment] 2016-10-29 09:44
I have merged the `next` branch into `master`.

It's using koa and react-router 4 now. Enjoy!

**Comment by omaksi** [comment] 2016-10-29 13:06
Looks like a thorough rewrite, very nice! 
btw. which package did you use for the benchmark?

**Comment by nightwolfz** [comment] 2016-10-30 01:52
I compiled this tool [gohttpbench](https://github.com/parkghost/gohttpbench) written in Go.

I'm back-porting changes from my other project [inferno-starter](https://github.com/nightwolfz/inferno-starter) which has 10 to 20 times better performance. It seems like just by using react-router v4, we lose a lot in performance although it's still an alpha version, so performance can only improve :)

**Closed as completed** 2016-11-16 09:32 UTC

**Comment by yangfan0095** [comment] 2017-05-19 06:07
https://github.com/reactjs/react-router-redux/issues/179
